version: "2.1"
services:
  db:
    build: docker/
    expose:
      - "5432"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    restart: always
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATA_BASE_URI: "postgresql://postgres:postgres@db:5432/postgres"
    ports:
      - "8000:8000"
    volumes:
      - .:/habitat
    entrypoint: ["sh", "start_api.sh"]
